version: '3.8'

services:
  mysqldb:
    image: mariadb:10.9.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PASS
      - MYSQL_PASSWORD=$DB_PASS
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d #Crear las tablas automaticamente al iniciar
      - ./mysql:/var/lib/mysql #Mantener la misma data de mi base de datos local

  #Servicio de notificaciones
  rabbitmq:
    image: rabbitmq:3.12.12-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=$AMQP_USER
      - RABBITMQ_DEFAULT_PASS=$AMQP_PASS
  
  api:
    depends_on:
      mysqldb:
        condition: service_started
          #rabbitmq:
          #condition: service_started
    build: 
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - $BACK_PUBLIC_PORT:$BACK_PORT
    environment:
      - DB_HOST=mysqldb
    command: npm run dev
    volumes:
     - ./src:/app/src
     - ./files:/app/files/
